language: Go

notifications:
  irc: "chat.freenode.net#restic"

go:
  - 1.3
  - 1.3.1
  - 1.3.2
  - 1.3.3
  - 1.4
  - 1.4.1
  - 1.4.2
  - tip

install:
  - go get -v -t ./...

script:
  - gofmt -l *.go */*.go */*/*.go
  - test -z "$(gofmt -l *.go */*.go */*/*.go)"
  - go build ./...
  - go test ./...
  - ./testsuite.sh
