language: go
sudo: false

matrix:
  include:
    - os: linux
      go: "1.9.x"
      env: RESTIC_TEST_FUSE=0 RESTIC_TEST_CLOUD_BACKENDS=0 RESTIC_BUILD_SOLARIS=0

    # only run fuse and cloud backends tests on Travis for the latest Go on Linux
    - os: linux
      go: "1.10.x"
      sudo: true

    - os: osx
      go: "1.10.x"
      env: RESTIC_TEST_FUSE=0 RESTIC_TEST_CLOUD_BACKENDS=0

branches:
  only:
    - master

notifications:
  irc:
    channels:
      - "chat.freenode.net#restic"
    on_success: change
    on_failure: change
    skip_join: true

install:
  - go version
  - export GOBIN="$GOPATH/bin"
  - export PATH="$PATH:$GOBIN"
  - go env

script:
  - go run run_integration_tests.go

after_success:
  - bash <(curl -s https://codecov.io/bash) -f all.cov
