language: go

go:
  - 1.3.3
  - 1.4.2

os:
  - linux
  - osx

env: GOX_OS="linux darwin openbsd freebsd"

notifications:
  irc:
    channels:
      - "chat.freenode.net#restic"
    on_success: change
    on_failure: change
    skip_join: true

install:
  - go version
  - export GOBIN="$GOPATH/bin"
  - export PATH="$PATH:$GOBIN"
  - export GOPATH="$GOPATH:${TRAVIS_BUILD_DIR}/Godeps/_workspace"
  - go env
  - go get github.com/mattn/goveralls
  - go get github.com/mitchellh/gox
  - gox -build-toolchain -os "$GOX_OS"

script:
  - gox -verbose -os "${GOX_OS}" -tags "release" ./cmd/restic
  - go run run_tests.go all.cov
  - GOARCH=386 RESTIC_TEST_INTEGRATION=0 go test ./...
  - goveralls -coverprofile=all.cov -service=travis-ci -repotoken "$COVERALLS_TOKEN" || true
  - gofmt -l *.go */*.go */*/*.go
  - test -z "$(gofmt -l *.go */*.go */*/*.go)"
