language: go
sudo: false

go:
  - 1.8.x
  - 1.9.x

os:
  - linux
  - osx

env:
  matrix:
    RESTIC_TEST_FUSE=0

matrix:
  exclude:
    - os: osx
      go: 1.8.x
    - os: linux
      go: 1.9.x
  include:
    - os: linux
      go: 1.9.x
      sudo: true
      env:
        RESTIC_TEST_FUSE=1

branches:
  only:
    - master

notifications:
  irc:
    channels:
      - "chat.freenode.net#restic"
    on_success: change
    on_failure: change
    skip_join: true

install:
  - go version
  - export GOBIN="$GOPATH/bin"
  - export PATH="$PATH:$GOBIN"
  - go env

script:
  - go run run_integration_tests.go

after_success:
  - bash <(curl -s https://codecov.io/bash) -f all.cov
