language: go
sudo: false

go:
  - 1.3.3
  - 1.4.2

os:
  - linux
  - osx

env: GOX_OS="linux darwin openbsd freebsd windows" GOX_ARCH="386 amd64 arm"

notifications:
  irc:
    channels:
      - "chat.freenode.net#restic"
    on_success: change
    on_failure: change
    skip_join: true

install:
  - go version
  - export GOBIN="$GOPATH/bin"
  - export PATH="$PATH:$GOBIN"
  - go env

script:
  - go run run_integration_tests.go

after_success:
  - goveralls -coverprofile=all.cov -service=travis-ci -repotoken "$COVERALLS_TOKEN" || true
