language: go

go:
  - 1.3.3
  - 1.4.2
  - release

os:
  - linux
  - osx

notifications:
  irc:
    channels:
      - "chat.freenode.net#restic"
    on_success: change
    on_failure: change

env: GOX_OS="linux darwin openbsd freebsd"

install:
  - go get github.com/mitchellh/gox
  - gox -build-toolchain -os "$GOX_OS"
  - go get -v -t ./...

script:
  - go build -ldflags "-s" ./...
  - go build -ldflags "-s" -o restic ./cmd/restic
  - sh -c 'cd cmd/restic && gox -verbose -os "$GOX_OS" && ls -al'
  - go test -v ./...
  - ./testsuite.sh
  - sh -c "cd backend && go test -v -test.sftppath /usr/lib/openssh/sftp-server ./..."
  - gofmt -l *.go */*.go */*/*.go
  - test -z "$(gofmt -l *.go */*.go */*/*.go)"
