language: go

go:
  - 1.3.3
  - 1.4.2

os:
  - linux
  - osx

env: SFTP_PATH="/usr/lib/openssh/sftp-server" GOX_OS="linux darwin openbsd freebsd"

notifications:
  irc:
    channels:
      - "chat.freenode.net#restic"
    on_success: change
    on_failure: change

install:
  - go get github.com/mattn/goveralls
  - go get github.com/mitchellh/gox
  - gox -build-toolchain -os "$GOX_OS"

script:
  - make restic
  - make gox
  - make test
  - make test-integration
  - make all.cov
  - goveralls -coverprofile=all.cov -service=travis-ci -repotoken "$COVERALLS_TOKEN"
  - gofmt -l *.go */*.go */*/*.go
  - test -z "$(gofmt -l *.go */*.go */*/*.go)"
