language: go
sudo: false

go:
  - 1.6.3
  - 1.7

os:
  - linux
  - osx

matrix:
  exclude:
    - os: osx
      go: 1.6.3

notifications:
  irc:
    channels:
      - "chat.freenode.net#restic"
    on_success: change
    on_failure: change
    skip_join: true

install:
  - go version
  - export GOBIN="$GOPATH/bin"
  - export PATH="$PATH:$GOBIN"
  - go env
  - ulimit -n 2048

script:
  - go run run_integration_tests.go

after_success:
  - GOPATH=$PWD:$PWD/vendor goveralls -coverprofile=all.cov -service=travis-ci -repotoken "$COVERALLS_TOKEN"
  - bash <(curl -s https://codecov.io/bash) -f all.cov
