language: go
go:
  - 1.3.3
  - 1.4.2
  - release

notifications:
  irc: "chat.freenode.net#restic"

install:
  - go get -v -t ./...

script:
  - gofmt -l *.go */*.go */*/*.go
  - test -z "$(gofmt -l *.go */*.go */*/*.go)"
  - go build -ldflags "-s" ./...
  - go build -ldflags "-s" -o restic ./cmd/restic
  - stat --printf='binary size: %s' restic
  - go test ./...
  - ./testsuite.sh
