clone_folder: c:\gopath\src\github.com\restic\restic

environment:
  GOPATH: c:\gopath;c:\gopath\src\github.com\restic\restic\Godeps\_workspace

install:
  - go version
  - go env

build_script:
  - go run run_integration_tests.go
