site_name: Documentation for restic
theme: readthedocs
markdown_extensions:
  - codehilite:
extra_css:
  - code.css
docs_dir: doc
pages:
  - Getting Started: index.md
  - User Manual: Manual.md
  - restic Design Document: Design.md
