# version format
version: "{build}"

# Operating system (build VM template)
os: Windows Server 2012 R2

clone_folder: c:\gopath\src\github.com\minio\minio-go

# environment variables
environment:
  GOPATH: c:\gopath
  GO15VENDOREXPERIMENT: 1

# scripts that run after cloning repository
install:
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env
  - go get -u github.com/golang/lint/golint
  - go get -u golang.org/x/tools/cmd/vet
  - go get -u github.com/remyoudompheng/go-misc/deadcode

# to run your custom scripts instead of automatic MSBuild
build_script:
  - go vet ./...
  - gofmt -s -l .
  - golint github.com/minio/minio-go...
  - deadcode
  - go test
  - go test -test.short -race

# to disable automatic tests
test: off

# to disable deployment
deploy: off
